/**
 * Food Data Central API
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * JSON for request body of 'search' POST request
 */
export interface FoodSearchCriteria { 
    /**
     * Search terms to use in the search. The string may also include standard [search operators](https://fdc.nal.usda.gov/help.html#bkmk-2)
     */
    query?: string;
    /**
     * Optional. Filter on a specific data type; specify one or more values in an array.
     */
    dataType?: Array<FoodSearchCriteria.DataTypeEnum>;
    /**
     * Optional. Maximum number of results to return for the current page. Default is 50.
     */
    pageSize?: number;
    /**
     * Optional. Page number to retrieve. The offset into the overall result set is expressed as (pageNumber * pageSize)
     */
    pageNumber?: number;
    /**
     * Optional. Specify one of the possible values to sort by that field. Note, dataType.keyword will be dataType and lowercaseDescription.keyword will be description in future releases.
     */
    sortBy?: FoodSearchCriteria.SortByEnum;
    /**
     * Optional. The sort direction for the results. Only applicable if sortBy is specified.
     */
    sortOrder?: FoodSearchCriteria.SortOrderEnum;
    /**
     * Optional. Filter results based on the brand owner of the food. Only applies to Branded Foods.
     */
    brandOwner?: string;
}
export namespace FoodSearchCriteria {
    export type DataTypeEnum = 'Branded' | 'Foundation' | 'Survey (FNDDS)' | 'SR Legacy';
    export const DataTypeEnum = {
        Branded: 'Branded' as DataTypeEnum,
        Foundation: 'Foundation' as DataTypeEnum,
        SurveyFNDDS: 'Survey (FNDDS)' as DataTypeEnum,
        SRLegacy: 'SR Legacy' as DataTypeEnum
    };
    export type SortByEnum = 'dataType.keyword' | 'lowercaseDescription.keyword' | 'fdcId' | 'publishedDate';
    export const SortByEnum = {
        DataTypeKeyword: 'dataType.keyword' as SortByEnum,
        LowercaseDescriptionKeyword: 'lowercaseDescription.keyword' as SortByEnum,
        FdcId: 'fdcId' as SortByEnum,
        PublishedDate: 'publishedDate' as SortByEnum
    };
    export type SortOrderEnum = 'asc' | 'desc';
    export const SortOrderEnum = {
        Asc: 'asc' as SortOrderEnum,
        Desc: 'desc' as SortOrderEnum
    };
}