/**
 * Food Data Central API
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AbridgedFoodItem } from '../model/abridgedFoodItem';
// import { AbridgedFoodItemBrandedFoodItemFoundationFoodItemSRLegacyFoodItemSurveyFoodItem } from '../model/abridgedFoodItemBrandedFoodItemFoundationFoodItemSRLegacyFoodItemSurveyFoodItem';
import { FoodListCriteria } from '../model/foodListCriteria';
import { FoodSearchCriteria } from '../model/foodSearchCriteria';
import { FoodsCriteria } from '../model/foodsCriteria';
import { InlineResponse200 } from '../model/inlineResponse200';
import { SearchResult } from '../model/searchResult';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BrandedFoodItem } from '../model/brandedFoodItem';
import { FoundationFoodItem } from '../model/foundationFoodItem';
import { SRLegacyFoodItem } from '../model/sRLegacyFoodItem';
import { SurveyFoodItem } from '../model/surveyFoodItem';


@Injectable()
export class FDCService {

    protected basePath = 'https://api.nal.usda.gov/fdc';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Fetches details for one food item by FDC ID
     * Retrieves a single food item by an FDC ID. Optional format and nutrients can be specified.
     * @param fdcId FDC id of the food to retrieve
     * @param format Optional. &#x27;abridged&#x27; for an abridged set of elements, &#x27;full&#x27; for all elements (default).
     * @param nutrients Optional. List of up to 25 nutrient numbers. Only the nutrient information for the specified nutrients will be returned. Should be comma separated list (e.g. nutrients&#x3D;203,204) or repeating parameters (e.g. nutrients&#x3D;203&amp;nutrients&#x3D;204). If a food does not have any matching nutrients, the food will be returned with an empty foodNutrients element.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFood(fdcId: string, format?: string, nutrients?: Array<number>, observe?: 'body', reportProgress?: boolean): Observable<InlineResponse200>;
    public getFood(fdcId: string, format?: string, nutrients?: Array<number>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InlineResponse200>>;
    public getFood(fdcId: string, format?: string, nutrients?: Array<number>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InlineResponse200>>;
    public getFood(fdcId: string, format?: string, nutrients?: Array<number>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fdcId === null || fdcId === undefined) {
            throw new Error('Required parameter fdcId was null or undefined when calling getFood.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (format !== undefined && format !== null) {
            queryParameters = queryParameters.set('format', <any>format);
        }
        if (nutrients) {
            nutrients.forEach((element) => {
                queryParameters = queryParameters.append('nutrients', <any>element);
            })
        }

        let headers = this.defaultHeaders;

        // authentication (ApiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["api_key"]) {
            queryParameters = queryParameters.set('api_key', this.configuration.apiKeys["api_key"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<InlineResponse200>('get',`${this.basePath}/v1/food/${encodeURIComponent(String(fdcId))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Fetches details for multiple food items using input FDC IDs
     * Retrieves a list of food items by a list of up to 20 FDC IDs. Optional format and nutrients can be specified. Invalid FDC ID&#x27;s or ones that are not found are omitted and an empty set is returned if there are no matches.
     * @param fdcIds List of multiple FDC ID&#x27;s. Should be comma separated list (e.g. fdcIds&#x3D;534358,373052) or repeating parameters (e.g. fdcIds&#x3D;534358&amp;fdcIds&#x3D;373052).
     * @param format Optional. &#x27;abridged&#x27; for an abridged set of elements, &#x27;full&#x27; for all elements (default).
     * @param nutrients Optional. List of up to 25 nutrient numbers. Only the nutrient information for the specified nutrients will be returned. Should be comma separated list (e.g. nutrients&#x3D;203,204) or repeating parameters (e.g. nutrients&#x3D;203&amp;nutrients&#x3D;204). If a food does not have any matching nutrients, the food will be returned with an empty foodNutrients element.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFoods(fdcIds: Array<string>, format?: string, nutrients?: Array<number>, observe?: 'body', reportProgress?: boolean): Observable<Array<AbridgedFoodItem | BrandedFoodItem | FoundationFoodItem | SRLegacyFoodItem | SurveyFoodItem>>;
    public getFoods(fdcIds: Array<string>, format?: string, nutrients?: Array<number>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AbridgedFoodItem | BrandedFoodItem | FoundationFoodItem | SRLegacyFoodItem | SurveyFoodItem>>>;
    public getFoods(fdcIds: Array<string>, format?: string, nutrients?: Array<number>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AbridgedFoodItem | BrandedFoodItem | FoundationFoodItem | SRLegacyFoodItem | SurveyFoodItem>>>;
    public getFoods(fdcIds: Array<string>, format?: string, nutrients?: Array<number>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fdcIds === null || fdcIds === undefined) {
            throw new Error('Required parameter fdcIds was null or undefined when calling getFoods.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (fdcIds) {
            fdcIds.forEach((element) => {
                queryParameters = queryParameters.append('fdcIds', <any>element);
            })
        }
        if (format !== undefined && format !== null) {
            queryParameters = queryParameters.set('format', <any>format);
        }
        if (nutrients) {
            nutrients.forEach((element) => {
                queryParameters = queryParameters.append('nutrients', <any>element);
            })
        }

        let headers = this.defaultHeaders;

        // authentication (ApiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["api_key"]) {
            queryParameters = queryParameters.set('api_key', this.configuration.apiKeys["api_key"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<AbridgedFoodItem | BrandedFoodItem | FoundationFoodItem | SRLegacyFoodItem | SurveyFoodItem>>('get',`${this.basePath}/v1/foods`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns a paged list of foods, in the &#x27;abridged&#x27; format
     * Retrieves a paged list of foods. Use the pageNumber parameter to page through the entire result set.
     * @param dataType Optional. Filter on a specific data type; specify one or more values in an array.
     * @param pageSize Optional. Maximum number of results to return for the current page. Default is 50.
     * @param pageNumber Optional. Page number to retrieve. The offset into the overall result set is expressed as (pageNumber * pageSize)
     * @param sortBy Optional. Specify one of the possible values to sort by that field. Note, dataType.keyword will be dataType and lowercaseDescription.keyword will be description in future releases.
     * @param sortOrder Optional. The sort direction for the results. Only applicable if sortBy is specified.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFoodsList(dataType?: Array<string>, pageSize?: number, pageNumber?: number, sortBy?: string, sortOrder?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<AbridgedFoodItem>>;
    public getFoodsList(dataType?: Array<string>, pageSize?: number, pageNumber?: number, sortBy?: string, sortOrder?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AbridgedFoodItem>>>;
    public getFoodsList(dataType?: Array<string>, pageSize?: number, pageNumber?: number, sortBy?: string, sortOrder?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AbridgedFoodItem>>>;
    public getFoodsList(dataType?: Array<string>, pageSize?: number, pageNumber?: number, sortBy?: string, sortOrder?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (dataType) {
            queryParameters = queryParameters.set('dataType', dataType.join(COLLECTION_FORMATS['csv']));
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }
        if (pageNumber !== undefined && pageNumber !== null) {
            queryParameters = queryParameters.set('pageNumber', <any>pageNumber);
        }
        if (sortBy !== undefined && sortBy !== null) {
            queryParameters = queryParameters.set('sortBy', <any>sortBy);
        }
        if (sortOrder !== undefined && sortOrder !== null) {
            queryParameters = queryParameters.set('sortOrder', <any>sortOrder);
        }

        let headers = this.defaultHeaders;

        // authentication (ApiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["api_key"]) {
            queryParameters = queryParameters.set('api_key', this.configuration.apiKeys["api_key"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<AbridgedFoodItem>>('get',`${this.basePath}/v1/foods/list`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns a list of foods that matched search (query) keywords
     * Search for foods using keywords. Results can be filtered by dataType and there are options for result page sizes or sorting.
     * @param query One or more search terms.  The string may include [search operators](https://fdc.nal.usda.gov/help.html#bkmk-2)
     * @param dataType Optional. Filter on a specific data type; specify one or more values in an array.
     * @param pageSize Optional. Maximum number of results to return for the current page. Default is 50.
     * @param pageNumber Optional. Page number to retrieve. The offset into the overall result set is expressed as (pageNumber * pageSize)
     * @param sortBy Optional. Specify one of the possible values to sort by that field. Note, dataType.keyword will be dataType and lowercaseDescription.keyword will be description in future releases.
     * @param sortOrder Optional. The sort direction for the results. Only applicable if sortBy is specified.
     * @param brandOwner Optional. Filter results based on the brand owner of the food. Only applies to Branded Foods
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFoodsSearch(query: string, dataType?: Array<string>, pageSize?: number, pageNumber?: number, sortBy?: string, sortOrder?: string, brandOwner?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<SearchResult>>;
    public getFoodsSearch(query: string, dataType?: Array<string>, pageSize?: number, pageNumber?: number, sortBy?: string, sortOrder?: string, brandOwner?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SearchResult>>>;
    public getFoodsSearch(query: string, dataType?: Array<string>, pageSize?: number, pageNumber?: number, sortBy?: string, sortOrder?: string, brandOwner?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SearchResult>>>;
    public getFoodsSearch(query: string, dataType?: Array<string>, pageSize?: number, pageNumber?: number, sortBy?: string, sortOrder?: string, brandOwner?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (query === null || query === undefined) {
            throw new Error('Required parameter query was null or undefined when calling getFoodsSearch.');
        }







        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (query !== undefined && query !== null) {
            queryParameters = queryParameters.set('query', <any>query);
        }
        if (dataType) {
            queryParameters = queryParameters.set('dataType', dataType.join(COLLECTION_FORMATS['csv']));
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }
        if (pageNumber !== undefined && pageNumber !== null) {
            queryParameters = queryParameters.set('pageNumber', <any>pageNumber);
        }
        if (sortBy !== undefined && sortBy !== null) {
            queryParameters = queryParameters.set('sortBy', <any>sortBy);
        }
        if (sortOrder !== undefined && sortOrder !== null) {
            queryParameters = queryParameters.set('sortOrder', <any>sortOrder);
        }
        if (brandOwner !== undefined && brandOwner !== null) {
            queryParameters = queryParameters.set('brandOwner', <any>brandOwner);
        }

        let headers = this.defaultHeaders;

        // authentication (ApiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["api_key"]) {
            queryParameters = queryParameters.set('api_key', this.configuration.apiKeys["api_key"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<SearchResult>>('get',`${this.basePath}/v1/foods/search`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns this documentation in JSON format
     * The OpenAPI 3.0 specification for the FDC API rendered as JSON (JavaScript Object Notation)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getJsonSpec(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getJsonSpec(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getJsonSpec(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getJsonSpec(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});

        let headers = this.defaultHeaders;

        // authentication (ApiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["api_key"]) {
            queryParameters = queryParameters.set('api_key', this.configuration.apiKeys["api_key"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/v1/json-spec`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns this documentation in JSON format
     * The OpenAPI 3.0 specification for the FDC API rendered as YAML (YAML Ain&#x27;t Markup Language)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getYamlSpec(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getYamlSpec(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getYamlSpec(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getYamlSpec(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});

        let headers = this.defaultHeaders;

        // authentication (ApiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["api_key"]) {
            queryParameters = queryParameters.set('api_key', this.configuration.apiKeys["api_key"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/v1/yaml-spec`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Fetches details for multiple food items using input FDC IDs
     * Retrieves a list of food items by a list of up to 20 FDC IDs. Optional format and nutrients can be specified. Invalid FDC ID&#x27;s or ones that are not found are omitted and an empty set is returned if there are no matches.
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postFoods(body: FoodsCriteria, observe?: 'body', reportProgress?: boolean): Observable<Array<AbridgedFoodItem | BrandedFoodItem | FoundationFoodItem | SRLegacyFoodItem | SurveyFoodItem>>;
    public postFoods(body: FoodsCriteria, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AbridgedFoodItem | BrandedFoodItem | FoundationFoodItem | SRLegacyFoodItem | SurveyFoodItem>>>;
    public postFoods(body: FoodsCriteria, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AbridgedFoodItem | BrandedFoodItem | FoundationFoodItem | SRLegacyFoodItem | SurveyFoodItem>>>;
    public postFoods(body: FoodsCriteria, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postFoods.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});

        let headers = this.defaultHeaders;

        // authentication (ApiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["api_key"]) {
            queryParameters = queryParameters.set('api_key', this.configuration.apiKeys["api_key"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<AbridgedFoodItem | BrandedFoodItem | FoundationFoodItem | SRLegacyFoodItem | SurveyFoodItem>>('post',`${this.basePath}/v1/foods`,
            {
                body: body,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns a paged list of foods, in the &#x27;abridged&#x27; format
     * Retrieves a paged list of foods. Use the pageNumber parameter to page through the entire result set.
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postFoodsList(body: FoodListCriteria, observe?: 'body', reportProgress?: boolean): Observable<Array<AbridgedFoodItem>>;
    public postFoodsList(body: FoodListCriteria, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AbridgedFoodItem>>>;
    public postFoodsList(body: FoodListCriteria, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AbridgedFoodItem>>>;
    public postFoodsList(body: FoodListCriteria, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postFoodsList.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});

        let headers = this.defaultHeaders;

        // authentication (ApiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["api_key"]) {
            queryParameters = queryParameters.set('api_key', this.configuration.apiKeys["api_key"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<AbridgedFoodItem>>('post',`${this.basePath}/v1/foods/list`,
            {
                body: body,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns a list of foods that matched search (query) keywords
     * Search for foods using keywords. Results can be filtered by dataType and there are options for result page sizes or sorting.
     * @param body The query string may also include standard [search operators](https://fdc.nal.usda.gov/help.html#bkmk-2)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postFoodsSearch(body: FoodSearchCriteria, observe?: 'body', reportProgress?: boolean): Observable<Array<SearchResult>>;
    public postFoodsSearch(body: FoodSearchCriteria, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SearchResult>>>;
    public postFoodsSearch(body: FoodSearchCriteria, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SearchResult>>>;
    public postFoodsSearch(body: FoodSearchCriteria, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postFoodsSearch.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});

        let headers = this.defaultHeaders;

        // authentication (ApiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["api_key"]) {
            queryParameters = queryParameters.set('api_key', this.configuration.apiKeys["api_key"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<SearchResult>>('post',`${this.basePath}/v1/foods/search`,
            {
                body: body,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
